# Generated by Django 3.2.9 on 2021-11-13 10:28

import blog.utils
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True, verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True, verbose_name='تگ')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='پیوند یکتا')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='موضوع')),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن اصلی')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.utils.get_image_path, validators=[blog.utils.image_size], verbose_name='تصویر')),
                ('status', models.CharField(choices=[(0, 'تایید'), (1, 'در حال بررسی'), (2, 'مردود')], default=0, max_length=10, verbose_name='وضعیت')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='accounts.profile', verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category', verbose_name='دسته بندی')),
                ('tag', models.ManyToManyField(blank=True, related_name='posts', to='blog.Tag', verbose_name='تگ')),
            ],
        ),
    ]
