# Generated by Django 3.2.9 on 2021-11-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'تایید'), (1, 'در حال بررسی'), (2, 'مردود')], default=1, verbose_name='وضعیت'),
        ),
    ]
